### ISSUE TITLE
TransitiveDependencyDetector: seems to not work with scoped imports that have paths in them

### ISSUE THREAD

**Issue by kenotron** [microsoft/boll#49]
TransitiveDependencyDetector seems to get tripped when it is looking at something like this:

```
@foo/bar/baz
```

Where the package name is `@foo/bar` and the path is `baz`

**Comment by jdhuntington** [comment]
Talked offline. Based on https://github.com/microsoft/boll/blob/main/packages/rules-typescript/src/transitive-dependency-detector.ts#L72 , this is likely ok as-built and another issue around deps vs depDeps was coming up in practice.

**Comment by kenotron** [comment]
I believe the error message was misleading me to think there's a bug in boll.
